version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://alexalexlex:123@postgres:5432/db
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: alexalexlex
      POSTGRES_DB: test
      NODE_ENV: development
      PORT: 8080
    ports:
      - "8080:8080"
    command: npm run start
    volumes:
      - .:/app/
      - /app/node_modules

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: alexalexlex
      POSTGRES_DB: test